"""added oauth related fields in user model

Revision ID: 1cd5b4e6294a
Revises: 326d80d2cdbb
Create Date: 2025-09-28 19:22:57.237935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd5b4e6294a'
down_revision: Union[str, Sequence[str], None] = '326d80d2cdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('google_oauth', sa.Boolean(), nullable=True))
    op.add_column('accounts', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('accounts', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'email_verified')
    op.drop_column('accounts', 'access_token')
    op.drop_column('accounts', 'google_oauth')
    # ### end Alembic commands ###
