"""Added is_deleted flag for Topic and Comment models

Revision ID: 22c13dfe8b65
Revises: 326d80d2cdbb
Create Date: 2025-09-28 11:13:12.997201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c13dfe8b65'
down_revision: Union[str, Sequence[str], None] = '326d80d2cdbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with a default of False so SQLite accepts it
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('topics', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'is_deleted')
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###
