"""empty message

Revision ID: 3dab0dc6b329
Revises: 8cf16a944298
Create Date: 2025-08-04 13:07:06.838446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dab0dc6b329'
down_revision: Union[str, Sequence[str], None] = '8cf16a944298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums') as batch_op:
        batch_op.alter_column('parent_id',
                existing_type=sa.INTEGER(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forums') as batch_op:
        batch_op.alter_column('parent_id',
                existing_type=sa.INTEGER(),
                nullable=False)
    # ### end Alembic commands ###
