"""altered forum added description column

Revision ID: 8cf16a944298
Revises: d35be2064a6e
Create Date: 2025-08-04 12:49:37.734268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf16a944298'
down_revision: Union[str, Sequence[str], None] = 'd35be2064a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forums', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forums', 'description')
    # ### end Alembic commands ###
