"""added can_change_username col to User model

Revision ID: c5121b01a65e
Revises: 1cd5b4e6294a
Create Date: 2025-10-01 10:25:08.227894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5121b01a65e'
down_revision: Union[str, Sequence[str], None] = '1cd5b4e6294a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('can_change_username', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'can_change_username')
    # ### end Alembic commands ###
