"""create vote models

Revision ID: d927eb3ee2bf
Revises: 739abb46cae8
Create Date: 2025-08-18 15:21:04.581881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd927eb3ee2bf'
down_revision: Union[str, Sequence[str], None] = '739abb46cae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_votes',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('UPVOTE', 'NOVOTE', 'DOWNVOTE', name='votetype'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'user_id')
    )
    op.create_table('comment_votes',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('UPVOTE', 'NOVOTE', 'DOWNVOTE', name='votetype'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    
    op.add_column('comments', sa.Column('score', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('topics',   sa.Column('score', sa.Integer(), nullable=False, server_default=sa.text('0')))

    op.execute("UPDATE forums SET description = '' WHERE description IS NULL")
    with op.batch_alter_table('forums') as batch_op:
        batch_op.alter_column(
            'description',
            existing_type=sa.TEXT(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'score')
    op.drop_column('comments', 'score')

    with op.batch_alter_table('forums') as batch_op:
        batch_op.alter_column(
            'description',
            existing_type=sa.TEXT(),
            nullable=True
        )

    op.drop_table('comment_votes')
    op.drop_table('topic_votes')
    # ### end Alembic commands ###
